### ISSUE TITLE
Android plugin crashes because API 31+ requires FLAG_IMMUTABLE or FLAG_MUTABLE to be specified when creating a PendingIntent

### ISSUE THREAD

**Issue by NorthFred** [ingageco/capacitor-music-controls-plugin-v3#1]
This plugin crashes on Android API 31+ with following error output during creation of the MusicControls:

```
V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 53320577, pluginId: CapacitorMusicControls, methodName: create
V/Capacitor: callback: 53320577, pluginId: CapacitorMusicControls, methodName: create, methodData: {"album":"My albun name","track":"Title name","artist":"Artist or band","isPlaying":true,"dismissable":true,"hasPrev":false,"hasNext":false,"hasClose":true}
D/Capacitor: Handling local request: http://localhost/svg/stop.svg
D/AAudioStream: setState(s#2) from 3 to 4
V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 53320578, pluginId: Http, methodName: request
V/Capacitor: callback: 53320578, pluginId: Http, methodName: request, methodData: {"url":"http:\/\/stream.radioxxxxxxxx.xx:1234\/stats?sid=1&json=1","method":"GET","headers":{"Accept":"application\/json"}}
W/MediaSessionCompat: Couldn't find a unique registered media button receiver in the given context.
**W/System.err: java.lang.IllegalArgumentException: xx.xxxxxxxxxx.radio: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
W/System.err: Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
W/System.err:     at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
W/System.err:     at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
W/System.err:     at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
W/System.err:     at com.ingageco.capacitormusiccontrols.CapacitorMusicControls.initialize(CapacitorMusicControls.java:148)
W/System.err:     at com.ingageco.capacitormusiccontrols.CapacitorMusicControls.create(CapacitorMusicControls.java:71)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138)
W/System.err:     at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:763)
W/System.err:     at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:938)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err:     at android.os.Looper.loopOnce(Looper.java:201)
W/System.err:     at android.os.Looper.loop(Looper.java:288)
W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:67)**
I/CMCNotification: updateNotification: infos: com.ingageco.capacitormusiccontrols.MusicControlsInfos@be409ef
E/Capacitor: Serious error executing plugin
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138)
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:763)
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
        at com.ingageco.capacitormusiccontrols.MusicControlsNotification.updateNotification(MusicControlsNotification.java:73)
        at com.ingageco.capacitormusiccontrols.CapacitorMusicControls.create(CapacitorMusicControls.java:80)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138) 
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:763) 
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
I/cmcapp:CMCNotifyKiller: onCreate
E/AndroidRuntime: FATAL EXCEPTION: CapacitorPlugins
    Process: xx.xxxxxxxxxx.radio, PID: 14572
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:772)
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138)
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:763)
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
        at com.ingageco.capacitormusiccontrols.MusicControlsNotification.updateNotification(MusicControlsNotification.java:73)
        at com.ingageco.capacitormusiccontrols.CapacitorMusicControls.create(CapacitorMusicControls.java:80)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138) 
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:763) 
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
I/CapacitorMusicControls: onServiceConnected
I/CapacitorMusicControls: service Started
I/Process: Sending signal. PID: 14572 SIG: 9

```

**Comment by ingageco** [comment]
Thanks @NorthFred - I went through and changed this for other PendingIntents but it looks like the one referenced needs to be changed as well.

**Comment by ingageco** [comment]
Try 1.0.11 or the most recent version of the main branch and see if this is resolved.

**Comment by NorthFred** [comment]
@ingageco I will verify this in a week from now, I just left on a trip. Appreciate your efforts!

**Comment by NorthFred** [comment]
Created a separate issue in https://github.com/ingageco/capacitor-music-controls-plugin-v3/issues/2 for this, because the PendingIntent has been resolved.
